# Generated by Django 5.2.4 on 2026-01-03 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=10)),
                ('result', models.CharField(choices=[('Real', 'Real'), ('Fake', 'Fake')], max_length=10)),
                ('confidence', models.FloatField()),
                ('frames_analyzed', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('frame_predictions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detection History',
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
